var createChessEngine=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var d=moduleArg,aa=!!globalThis.window,n=!!globalThis.WorkerGlobalScope;n&&(_scriptName=self.location.href);var p="",q,r;if(aa||n){try{p=(new URL(".",_scriptName)).href}catch{}n&&(r=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});q=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var t=console.error.bind(console),u,v=!1,w,x,y,z,A,B,C=!1;
function D(){var a=E.buffer;z=new Int8Array(a);new Int16Array(a);A=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);new Uint32Array(a);new Float32Array(a);new Float64Array(a);B=new BigInt64Array(a);new BigUint64Array(a)}function F(a){d.onAbort?.(a);a="Aborted("+a+")";t(a);v=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");y?.(a);throw a;}var G;
async function ba(a){if(!u)try{var b=await q(a);return new Uint8Array(b)}catch{}if(a==G&&u)a=new Uint8Array(u);else if(r)a=r(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(e){t(`failed to asynchronously prepare wasm: ${e}`),F(e)}}
async function da(a){var b=G;if(!u)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){t(`wasm streaming compile failed: ${e}`),t("falling back to ArrayBuffer instantiation")}return ca(b,a)}class H{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var I=a=>{for(;0<a.length;)a.shift()(d)},J=[],K=[],ea=()=>{var a=d.preRun.shift();K.push(a)},L=!0,M=0,N={},O=a=>{if(!(a instanceof H||"unwind"==a))throw a;},P=a=>{w=a;L||0<M||(d.onExit?.(a),v=!0);throw new H(a);},fa=a=>{if(!v)try{if(a(),!(L||0<M))try{w=a=w,P(a)}catch(b){O(b)}}catch(b){O(b)}},Q=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},R=(a,b,c)=>{var e=A;if(0<c){c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);
if(127>=f){if(b>=c)break;e[b++]=f}else if(2047>=f){if(b+1>=c)break;e[b++]=192|f>>6;e[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;e[b++]=224|f>>12;e[b++]=128|f>>6&63;e[b++]=128|f&63}else{if(b+3>=c)break;e[b++]=240|f>>18;e[b++]=128|f>>12&63;e[b++]=128|f>>6&63;e[b++]=128|f&63;g++}}e[b]=0}},S=globalThis.TextDecoder&&new TextDecoder,T=(a=0,b,c)=>{var e=A;var g=a;b=g+b;if(c)c=b;else{for(;e[g]&&!(g>=b);)++g;c=g}if(16<c-a&&e.buffer&&S)return S.decode(e.subarray(a,c));for(g="";a<c;)if(b=e[a++],b&128){var f=
e[a++]&63;if(192==(b&224))g+=String.fromCharCode((b&31)<<6|f);else{var l=e[a++]&63;b=224==(b&240)?(b&15)<<12|f<<6|l:(b&7)<<18|f<<12|l<<6|e[a++]&63;65536>b?g+=String.fromCharCode(b):(b-=65536,g+=String.fromCharCode(55296|b>>10,56320|b&1023))}}else g+=String.fromCharCode(b);return g},ha=(a,b,c,e)=>{var g={string:h=>{var k=0;if(null!==h&&void 0!==h&&0!==h){k=Q(h)+1;var W=U(k);R(h,W,k);k=W}return k},array:h=>{var k=U(h.length);z.set(h,k);return k}};a=d["_"+a];var f=[],l=0;if(e)for(var m=0;m<e.length;m++){var X=
g[c[m]];X?(0===l&&(l=V()),f[m]=X(e[m])):f[m]=e[m]}c=a(...f);return c=function(h){0!==l&&Y(l);return"string"===b?h?T(h):"":"boolean"===b?!!h:h}(c)};d.noExitRuntime&&(L=d.noExitRuntime);d.printErr&&(t=d.printErr);d.wasmBinary&&(u=d.wasmBinary);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();d.ccall=ha;d.cwrap=(a,b,c,e)=>{var g=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&g&&!e?d["_"+a]:(...f)=>ha(a,b,c,f,e)};
d.UTF8ToString=(a,b,c)=>a?T(a,b,c):"";d.stringToNewUTF8=a=>{var b=Q(a)+1,c=ia(b);c&&R(a,c,b);return c};
var ia,ja,Y,U,V,E,ka={c:()=>F(""),b:()=>{L=!1;M=0},d:(a,b)=>{N[a]&&(clearTimeout(N[a].id),delete N[a]);if(!b)return 0;var c=setTimeout(()=>{delete N[a];fa(()=>ja(a,performance.now()))},b);N[a]={id:c,A:b};return 0},f:function(a,b,c){if(!(0<=a&&3>=a))return 28;B[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},e:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,
e)/65536))-E.buffer.byteLength+65535)/65536|0;try{E.grow(e);D();var g=1;break a}catch(f){}g=void 0}if(g)return!0}return!1},a:P},Z;
Z=await (async function(){function a(c){c=Z=c.exports;d._wasm_init=c.i;d._wasm_clear=c.j;d._wasm_load_fen=c.k;d._wasm_search=c.l;d._free=c.m;d._wasm_get_depth=c.n;d._wasm_get_nodes=c.o;d._wasm_get_time=c.p;d._wasm_get_nps=c.q;d._wasm_is_timeout=c.r;d._wasm_eval=c.s;ia=d._malloc=c.t;ja=c.u;Y=c.v;U=c.w;V=c.x;E=c.g;D();return Z}var b={a:ka};if(d.instantiateWasm)return new Promise(c=>{d.instantiateWasm(b,(e,g)=>{c(a(e,g))})});G??=d.locateFile?d.locateFile("feohzero.wasm",p):p+"feohzero.wasm";
return a((await da(b)).instance)}());(function(){function a(){d.calledRun=!0;if(!v){C=!0;Z.h();x?.(d);d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();J.push(b)}I(J)}}if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ea();I(K);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();
C?moduleRtn=d:moduleRtn=new Promise((a,b)=>{x=a;y=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createChessEngine;module.exports.default=createChessEngine}else if(typeof define==="function"&&define["amd"])define([],()=>createChessEngine);
